//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoTSkillZ.Models.Giveaway.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Giveaway
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Rules { get; set; }
        public bool International { get; set; }
        public bool Sponsored { get; set; }
        public Nullable<int> TotalEntries { get; set; }
        public string ImageUrl { get; set; }
        public string VideoUrl { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Code { get; set; }
    }
}
