//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoTSkillZ.Models.YouTube.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class YouTubePlaylist
    {
        public int Id { get; set; }
        public string PlaylistId { get; set; }
        public string PlaylistTitle { get; set; }
        public string PlayListDescription { get; set; }
        public string ChannelId { get; set; }
        public string DefaultThumbnail { get; set; }
        public string MediumThumbnail { get; set; }
        public string HighThumbnail { get; set; }
        public string MaxThumbnail { get; set; }
        public string CustomThumbail { get; set; }
        public int PlaylistItemCount { get; set; }
        public bool PlaylistActive { get; set; }
        public System.DateTime PlaylistCreatedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
