//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoTSkillZ.Models.YouTube.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class YouTubeSuperChatList
    {
        public int Id { get; set; }
        public string Channeld { get; set; }
        public string ChannelUrl { get; set; }
        public string DisplayName { get; set; }
        public string CommentText { get; set; }
        public string Currency { get; set; }
        public string DisplayString { get; set; }
        public string AmountMicros { get; set; }
        public string ProfileImageUrl { get; set; }
        public Nullable<int> MessageType { get; set; }
        public Nullable<bool> IsSuperStickerEvent { get; set; }
        public string StickerId { get; set; }
        public string altText { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string YouTubeSuperChatId { get; set; }
        public Nullable<bool> ShowSuperChat { get; set; }
        public string CreatedAt { get; set; }
    }
}
