//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoTSkillZ.Models.CSGO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSGOVideoConfiguration
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string ColorMode { get; set; }
        public string Brightness { get; set; }
        public string AspectRatio { get; set; }
        public string Resolution { get; set; }
        public string DisplayMode { get; set; }
        public string LaptopPowerSavings { get; set; }
        public string GlobalShadowQuality { get; set; }
        public string ModelTextureDetail { get; set; }
        public string EffectDetail { get; set; }
        public string ShaderDetail { get; set; }
        public string MultiCoreRendering { get; set; }
        public string MultisamplingAntiAliasingMode { get; set; }
        public string FXXAAAnti_Aliasing { get; set; }
        public string TextureFilteringMode { get; set; }
        public string WaitForVerticalSync { get; set; }
        public string MotionBlur { get; set; }
        public string TripleMonitorMode { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string GameView { get; set; }
    }
}
