//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoTSkillZ.Models.CSGO.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GoTSkillZCSGOVideoConfigurationEntities : DbContext
    {
        public GoTSkillZCSGOVideoConfigurationEntities()
            : base("name=GoTSkillZCSGOVideoConfigurationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CSGOVideoConfiguration> CSGOVideoConfigurations { get; set; }
    }
}
