//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoTSkillZ.Models.Donation.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Name { get; set; }
        public string DonationType { get; set; }
        public string DonationTitle { get; set; }
        public string DonationDescription { get; set; }
        public string Amount { get; set; }
        public string CustomImgUrl { get; set; }
        public Nullable<System.DateTime> DonationDate { get; set; }
        public bool IsActive { get; set; }
    }
}
