//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoTSkillZ.Models.UserDataExtension.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfileExtension
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Alias { get; set; }
        public string About { get; set; }
        public string PrimaryGame { get; set; }
        public string SecondaryGame { get; set; }
        public string PrimaryRole { get; set; }
        public string SecondaryRole { get; set; }
        public string Status { get; set; }
        public string CurrentTeam { get; set; }
        public string PrimaryGameExp { get; set; }
        public string SecondaryGameExp { get; set; }
    }
}
