//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoTSkillZ.Models.UserDataExtension.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSocialLinks
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Facebook { get; set; }
        public string Instagram { get; set; }
        public string Twitter { get; set; }
        public string Steam { get; set; }
        public string YouTube { get; set; }
        public string Faceit { get; set; }
        public string SoStronk { get; set; }
        public string Twitch { get; set; }
        public string Mixer { get; set; }
        public string Discord { get; set; }
    }
}
