//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoTSkillZ.Models.UserDataExtension.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTeamHistory
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string TeamName { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
    }
}
