//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoTSkillZ.Models.Game.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GamePlatformConnectivity
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string SteamId { get; set; }
        public string SteamId64 { get; set; }
        public string FaceitId { get; set; }
        public string SoStronkId { get; set; }
        public string ESEA { get; set; }
        public string ESLId { get; set; }
    }
}
