//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoTSkillZ.Models.UserSetup.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupOption
    {
        public int Id { get; set; }
        public int SetupTypeId { get; set; }
        public string SetupOption1 { get; set; }
        public string Icon { get; set; }
    }
}
