//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoTSkillZ.Models.Membership.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class YouTubeChannelStatistic
    {
        public int Id { get; set; }
        public Nullable<int> SubCount { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<int> CommentCount { get; set; }
        public Nullable<bool> HiddenSubCount { get; set; }
        public Nullable<int> VideoCount { get; set; }
    }
}
